name: CI Windows

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: vcpkg install glfw3 glm nlohmann-json
    - name: Build
      run: |
        mkdir build && cd build
        echo $End:VCPKG_INSTALLATION_ROOT
        cmake .. -DCMAKE_BUILD_TYPE=Release -DGF_USE_EXTERNAL_JSON=ON -DCMAKE_TOOLCHAIN_FILE=$Env:VCPKG_INSTALLATION_ROOT\scripts\buildsystems
        cmake --build .
