name: CI macOS

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: brew install glfw glm nlohmann-json
    - name: Build
      run: |
        mkdir build && cd build
        cmake .. -DGF_USE_EXTERNAL_JSON=ON
        cmake --build . --parallel 4 --target install --config Release
