name: Build

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'

jobs:
  Windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
    - name: Install glfw
      run: |
        mkdir deps
        cd deps
        git clone https://github.com/glfw/glfw.git
        cd glfw
        mkdir build
        cd build
        cmake .. -DCMAKE_INSTALL_PREFIX=C:\software -DGLFW_BUILD_EXAMPLES=OFF -DGLFW_BUILD_TESTS=OFF -DGLFW_BUILD_DOCS=OFF
        cmake --build . --target install --config Release
    - name: Install glm
      run: |
        cd deps
        git clone https://github.com/g-truc/glm    
        cd glm
        git checkout 0.9.9.6
        mkdir build
        cd build
        cmake .. -DGLM_TEST_ENABLE=OFF -DCMAKE_INSTALL_PREFIX=C:\software
        cmake --build . --target install --config Release
    - uses: actions/checkout@v1
    - name: Build
      run: |
        mkdir build
        cd build
        cmake .. -DGF_USE_EXTERNAL_JSON=OFF -DCMAKE_PREFIX_PATH=C:\software
        cmake --build . --parallel 4 --target install --config Release

  Ubuntu:
    name: Build Ubuntu
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Get cmake 3.15
      run: |
        wget https://github.com/Kitware/CMake/releases/download/v3.15.2/cmake-3.15.2-Linux-x86_64.tar.gz
        tar -zxf cmake-3.15.2-Linux-x86_64.tar.gz
    - name: Install dependencies with apt
      run: |
        sudo apt-get update
        sudo apt-get install libglm-dev libgtk2.0-dev libxrandr-dev
    - name: Install gflw 3.3
      run: |
        git clone https://github.com/glfw/glfw.git
        cd glfw
        git checkout 3.3-stable
        mkdir build && cd build
        cmake .. -DGLFW_BUILD_EXAMPLES=OFF -DGLFW_BUILD_TESTS=OFF -DGLFW_BUILD_DOCS=OFF
        sudo cmake --build . --target install --config Release
    - name: Build
      run: |
        mkdir build && cd build
        ../cmake-3.15.2-Linux-x86_64/bin/cmake .. -DGF_USE_EXTERNAL_JSON=OFF -DCMAKE_INSTALL_PREFIX=~/usr
        ../cmake-3.15.2-Linux-x86_64/bin/cmake --build . --parallel 4 --target install --config Release

  macOS:
    name: Build macOS
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: brew install glfw glm nlohmann-json
    - name: Build
      run: |
        mkdir build && cd build
        cmake .. -DGF_USE_EXTERNAL_JSON=ON
        cmake --build . --parallel 4 --target install --config Release
